# Generated by Django 5.2.10 on 2026-03-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitems',
            name='description',
        ),
    ]
