# Generated by Django 5.2.10 on 2026-03-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_listitems_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitems',
            name='completed',
        ),
    ]
